server:
  port: 8080 # 服务绑定的端口，不写默认是8080
  servlet:
    context-path: /opms #路径，不写默认为空
spring:
  application:
    name: 外包管理平台
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: devManage
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/OPMSDB

